# Inbest.ai frontend CI
name: Inbest.ai continuous integration frontend

permissions:
  contents: read
  id-token: write

env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
  REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
  REMOTE_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
  REMOTE_PASSPHRASE: ${{ secrets.REMOTE_PASSPHRASE }}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Npm install
        run: npm ci

      - name: Run prettier
        run: npx prettier --check .

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'hivenote'
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Use gcloud CLI
        run: 'gcloud info'

      - name: publish
        run: |
          sh publish.sh

  